In [41]:
import numpy as np
import pandas as pd

In [42]:
np.random.seed(42)

In [43]:
num_employees = 1000

In [45]:
employee_id = np.arange(1001, 1001 + num_employees)

In [46]:
experience = experience.astype(float)

In [47]:
print(experience.dtype)

float64

In [48]:
experience[missing_indices] = np.nan

In [49]:
first_names = [
    "aarav","Vivaan","aditya","Ananya","priya",
    "Rahul","Sneha","Riya","Karan","Arjun",
    "Neha","Aisha","Rohan","simran","Kabir"
]

last_names = [
    "Sharma","Verma","singh","Patel","Gupta",
    "Maurya","yadav","Jain","Kumar","mehta"
]

In [50]:
names = [
    np.random.choice(first_names) + " " + np.random.choice(last_names)
    for _ in range(num_employees)
]

In [51]:
gender = np.random.choice(
    ["male","Female","Male","female","M","F"],
    size=num_employees
)

In [52]:
age = np.random.randint(
    21,
    60,
    
    num_employees
)

In [53]:
departments = np.random.choice(
    [
        "it",
        "HR",
        "finance",
        "Sales",
        "Marketing"
    ],
    size=num_employees
)

In [54]:
designations = np.random.choice(
    [
        "Intern",
        "EXecutive",
        "Analyst",
        "senior Analyst",
        "manager"
    ],
    size=num_employees
)

In [55]:
experience = np.random.randint(
    0,
    20,
    num_employees
)

In [56]:
salary = np.random.randint(
    25000,
    150001,
    num_employees
)

In [57]:
performance = np.random.choice(
    [
        "excellent",
        "GOOD",
        "average",
        "Poor"
    ],
    size=num_employees,
    p=[0.2,0.4,0.3,0.1]
)

In [58]:
attendance = np.random.uniform(
    70,
    100,
    num_employees
).round(2)

In [59]:
cities = np.random.choice(
    [
        "DELHI",
        "Mumbai",
        "lucknow",
        "Pune",
        "Bangalore",
        "Jaipur",
        "HyderaBad",
        "chennai"
    ],
    size=num_employees
)

In [60]:
joining_date = pd.to_datetime(
    np.random.choice(
        pd.date_range(
            "2018-01-01",
            "2025-01-01"
        ),
        num_employees
    )
)

In [61]:
work_mode = np.random.choice(
    [
        "OFFICE",
        "Hybrid",
        "remote"
    ],
    size=num_employees
)

In [63]:
overtime = np.random.randint(
    0,
    31,
    num_employees
)

In [64]:
training = np.random.randint(
    5,
    51,
    num_employees
)

In [65]:
df = pd.DataFrame({
    "Employee_ID": employee_id,
    "Name": names,
    "Gender": gender,
    "Age": age,
    "Department": departments,
    "Designation": designations,
    "Experience_Years": experience,
    "Salary": salary,
    "Performance_Rating": performance,
    "Attendance": attendance,
    "City": cities,
    "Joining_Date": joining_date,
    "Work_Mode": work_mode,
    "Overtime_Hours": overtime,
    "Training_Hours": training
})

In [66]:
df.head()

,Employee_ID,Name,Gender,Age,Department,Designation,Experience_Years,Salary,Performance_Rating,Attendance,City,Joining_Date,Work_Mode,Overtime_Hours,Training_Hours
0,1001,Sneha Patel,Male,51,Sales,Intern,18,71015,GOOD,71.50,Bangalore,2020-11-18,OFFICE,21,9
1,1002,Rohan Jain,Male,40,it,senior Analyst,2,127877,average,88.10,chennai,2019-12-15,remote,13,41
2,1003,Rohan Gupta,M,44,Marketing,senior Analyst,6,40339,average,94.20,Bangalore,2019-11-19,remote,10,35
3,1004,Sneha mehta,M,45,HR,manager,13,28491,GOOD,74.71,Mumbai,2018-11-26,OFFICE,22,16
4,1005,aditya yadav,F,56,Sales,Intern,13,25706,GOOD,70.45,lucknow,2022-10-13,remote,10,39

In [67]:
df.describe()

,Employee_ID,Age,Experience_Years,Salary,Attendance,Joining_Date,Overtime_Hours,Training_Hours
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.000000,1000.000000
mean,1500.500000,40.379000,9.659000,87457.742000,85.306190,2021-07-11 22:39:21.600000,15.247000,26.754000
min,1001.000000,21.000000,0.000000,25229.000000,70.090000,2018-01-03 00:00:00,0.000000,5.000000
25%,1250.750000,31.000000,5.000000,57220.750000,78.135000,2019-10-11 12:00:00,8.000000,15.000000
50%,1500.500000,41.000000,10.000000,87523.500000,85.550000,2021-07-06 12:00:00,15.000000,26.000000
75%,1750.250000,50.000000,15.000000,117843.750000,93.000000,2023-04-23 12:00:00,23.000000,38.000000
max,2000.000000,59.000000,19.000000,149647.000000,99.950000,2024-12-28 00:00:00,30.000000,50.000000
std,288.819436,11.108139,5.791741,35178.442004,8.714869,NaN,8.814061,13.187623

In [68]:
df.to_csv("data/employee_data.csv", index=False)